services:
  gatewaylextaticoapi:
    image: ${DOCKER_REGISTRY-}gatewaylextaticoapi
    container_name: gateway_lextatico_api
    build:
      context: .
      dockerfile: src/Gateway.Lextatico.Api/Dockerfile
    ports:
      - 7000:7000
      - 7001:7001
    networks:
      - Lextatico
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LOCAL_DEVELOPMENT=True
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  rabbitmq3:
    container_name: "gateway_lextatico_rabbitmq3"
    image: rabbitmq:3.9-management-alpine
    networks:
      - Lextatico
    environment:
      - RABBITMQ_DEFAULT_USER=lextatico
      - RABBITMQ_DEFAULT_PASS=L&xtat1c02021
    volumes:
        - rabbitmqdata:/var/lib/rabbitmq/
        - rabbitmqlog:/var/log/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: gateway_lextatico_sqlserver
    environment:
      - SA_PASSWORD=L&xt@t1c02021
      - ACCEPT_EULA=Y
    volumes:
      - sqlserverdata:/var/opt/mssql
    ports:
      - 1433:1433
    networks:
      - Lextatico
        
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: lextatico
      MONGO_INITDB_ROOT_PASSWORD: L&xtat1c02021
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - Lextatico
        
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: lextatico
      ME_CONFIG_MONGODB_ADMINPASSWORD: L&xtat1c02021
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "8082:8081"
    networks:
      - Lextatico
        
  seq:
    image: datalust/seq:latest
    container_name: seq
    depends_on:
      - gatewaylextaticoapi
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
    networks:
      - Lextatico
    cap_drop:
      - NET_RAW
