services:
  gatewaylextaticoapi:
    environment:
      - IS_DOCKER=True
      - ASPNETCORE_Kestrel__Certificates__Default__Password=lextatico
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Lextatico.pfx
    volumes:
      - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - /ASP.NET/Https:/https:ro

volumes:
  sqlserverdata:
    external: false
  rabbitmqdata:
    external: false
  rabbitmqlog:
    external: false
  mongodata:
    external: false

networks:
  Lextatico:
    external: true
    driver: bridge
