FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 7000
EXPOSE 7001

ENV ASPNETCORE_URLS=http://+:7000;https://+:7001

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
# RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
# USER appuser

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["src/Gateway.Lextatico.Api/Gateway.Lextatico.Api.csproj", "src/Gateway.Lextatico.Api/"]
RUN dotnet restore "src/Gateway.Lextatico.Api/Gateway.Lextatico.Api.csproj"
COPY . .
WORKDIR "/src/src/Gateway.Lextatico.Api"
RUN dotnet build "Gateway.Lextatico.Api.csproj" -c Debug -o /app/build

FROM build AS publish
RUN dotnet publish "Gateway.Lextatico.Api.csproj" -c Debug -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Gateway.Lextatico.Api.dll"]
